FIXES: "author" => "dct:creator" API/cavers/{id} - "comments": { "@id": "sioc:container_of"
-  l'idée c'est que plus créer des URI pour des choses qui ne sont pas dans l'API et n'y seront probablement jamais, comme les commentaires locaux sur une grottes ; alors il faut avoir des noeuds anonymes
- "@base" beginning with ../ creates the right URL's in output
- "descriptions": {  "@id": "karstlink:hasDescriptionDocument"
- "caves" "karstlink:relatedToUndergroundCavity"

TODO  "reviewer" , "names" , "county" etc
TESTED with
http://localhost:9000/json2rdf?context=file:///home/jmv/ontologies/Karstlink-ontology/grottocenter.org_context.jsonld&src=https://beta.grottocenter.org/api/v1/caves/5
http://localhost:9000/json2rdf?context=file:///home/jmv/ontologies/Karstlink-ontology/grottocenter.org_context.jsonld&src=https://beta.grottocenter.org/api/v1/entrances/4
TODO SF problem
http://localhost:9000/json2rdf?context=file:///home/jmv/ontologies/Karstlink-ontology/grottocenter.org_context.jsonld&src=file:///home/jmv/data/grottocenter.org/massif_3.json
java.lang.IllegalArgumentException: The provided content type is null.